---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: 3.3.0
serverless_language: node
polling_url: "{{ topic }}"
polling_headers: ''
polling_body: ''
id: 459683
oauth_enabled: 'false'
oauth_pkce_enabled: 'no'
oauth_authorize_url: ''
oauth_token_url: ''
oauth_scopes: ''
oauth_scope_separator: ''
oauth_refresh_url: ''
oauth_auth_params: ''
oauth_token_headers: ''
oauth_token_site: ''
oauth_token_params: ''
oauth_token_request_auth_method: ''
oauth_body_format: ''
oauth_token_response_metadata: ''
oauth_authorization_method: ''
oauth_refresh_params: ''
oauth_token_field_name: ''
oauth_expiry_field_name: ''
oauth_expiry_strategy: ''
oauth_fixed_expiry_ms: ''
custom_fields:
- keyname: about
  field_type: author_bio
  name: Público - Latest News
  github_url: https://github.com/mcduarte2000/trmnl-publico
  email_address: home.publicotrmnlplugin@miguelduarte.net
  category: news
  description: Público news feed (Portuguese)
- keyname: topic
  field_type: select
  options:
  - Geral: http://feeds.feedburner.com/PublicoRSS
  - Ciência: http://feeds.feedburner.com/PublicoCiencias
  - Cultura: http://feeds.feedburner.com/Publicocultura
  - Economia: http://feeds.feedburner.com/PublicoEconomia
  - Local: http://feeds.feedburner.com/PublicoLocal
  - Media: http://feeds.feedburner.com/Publico-Media
  - Mundo: http://feeds.feedburner.com/PublicoMundo
  - P3: http://feeds.feedburner.com/PublicoP3
  - Sociedade: http://feeds.feedburner.com/PublicoSociedade
  - Tecnologia: http://feeds.feedburner.com/PublicoTecnologia
  default: http://feeds.feedburner.com/PublicoRSS
  name: Topic
name: Público
description: Latest news from Público (PT)
refresh_interval: 30
